// <auto-generated />
namespace CcaRegistrationDf.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsActiveforSession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsActiveforSession));
        
        string IMigrationMetadata.Id
        {
            get { return "201504171307574_IsActive for Session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
