//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcaRegistrationDf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SEATSEntities : DbContext
    {
        public SEATSEntities()
            : base("name=SEATSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Category> Category1Set { get; set; }
        public virtual DbSet<Course> Courses1 { get; set; }
        public virtual DbSet<EnrollmentLocation> EnrollmentLocation1Set { get; set; }
        public virtual DbSet<MainTable> MainTable1Set { get; set; }
        public virtual DbSet<OnlineProvider> OnlineProvider1Set { get; set; }
        public virtual DbSet<Session> Session1Set { get; set; }
    }
}
